"use client";

import { ChangeEvent, useMemo, useState } from "react";

type Metrics={throughput:number;dispatch:number;pickAccuracy:number;inventoryAccuracy:number;dockToStock:number;spaceUtilization:number;lateInbound:number;costPerOrder:number};
type MetricKey=keyof Metrics;
type MetricConfig={key:MetricKey;label:string;unit:string;regional:[number,number];global:[number,number];higherBetter:boolean;target:string};
type Constraint={id:string;label:string;category:string;severity:"critical"|"high"|"watch"|"healthy";value:string;x:number;y:number;reason:string};
type UploadSummary={facility:string;region:string;period:string;rows:number;files:string[]};

const configs:MetricConfig[]=[
  {key:"throughput",label:"Lines per labour hour",unit:"",regional:[14.8,2.5],global:[16.2,3.1],higherBetter:true,target:"> 15.0"},
  {key:"dispatch",label:"On-time dispatch",unit:"%",regional:[95.0,3.0],global:[96.1,2.4],higherBetter:true,target:"> 95%"},
  {key:"pickAccuracy",label:"Pick accuracy",unit:"%",regional:[99.25,.5],global:[99.38,.42],higherBetter:true,target:"> 99.2%"},
  {key:"inventoryAccuracy",label:"Inventory accuracy",unit:"%",regional:[98.5,1.1],global:[98.9,.9],higherBetter:true,target:"> 98.5%"},
  {key:"dockToStock",label:"Dock-to-stock",unit:" hrs",regional:[5.8,2.2],global:[4.9,2.0],higherBetter:false,target:"< 6 hrs"},
  {key:"spaceUtilization",label:"Space utilisation",unit:"%",regional:[83,7],global:[81,8],higherBetter:false,target:"80–88%"},
  {key:"lateInbound",label:"Late inbound",unit:"%",regional:[9.5,5],global:[7.8,4.5],higherBetter:false,target:"< 10%"},
  {key:"costPerOrder",label:"Cost per order",unit:" AUD",regional:[7.85,1.4],global:[7.2,1.6],higherBetter:false,target:"< $8.00"},
];

const defaultMetrics:Metrics={throughput:11.5,dispatch:89.4,pickAccuracy:98.22,inventoryAccuracy:96.5,dockToStock:10.1,spaceUtilization:94.2,lateInbound:23.1,costPerOrder:9.4};
const defaultSummary:UploadSummary={facility:"Eastport Consumer Logistics",region:"Sydney · ANZ",period:"1–28 August 2026",rows:45,files:["warehouse daily","transport lanes","inventory snapshot"]};

function erf(value:number){const sign=value<0?-1:1;const x=Math.abs(value);const t=1/(1+.3275911*x);const y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x);return sign*y}
function percentile(value:number,[mean,sd]:[number,number],higherBetter:boolean){const z=(value-mean)/sd;const raw=.5*(1+erf(z/Math.sqrt(2)));return Math.max(1,Math.min(99,Math.round((higherBetter?raw:1-raw)*100)))}
function mean(rows:Record<string,string>[],key:string){const values=rows.map(row=>Number(row[key])).filter(Number.isFinite);return values.length?values.reduce((a,b)=>a+b,0)/values.length:0}
function parseCsv(text:string){const [header,...lines]=text.trim().split(/\r?\n/);const keys=header.split(",").map(value=>value.trim());return lines.filter(Boolean).map(line=>{const values=line.split(",");return Object.fromEntries(keys.map((key,index)=>[key,values[index]?.trim()??""]))})}

function analyse(files:Array<{name:string;rows:Record<string,string>[]}>){
  const warehouse=files.find(file=>"order_lines" in (file.rows[0]??{}));
  const inventory=files.find(file=>"sku_category" in (file.rows[0]??{}));
  if(!warehouse)throw new Error("Upload a warehouse daily CSV containing order_lines and labor_hours.");
  const rows=warehouse.rows;const totalLines=rows.reduce((sum,row)=>sum+Number(row.order_lines||0),0);const totalHours=rows.reduce((sum,row)=>sum+Number(row.labor_hours||0),0);
  const metrics:Metrics={throughput:totalHours?totalLines/totalHours:0,dispatch:mean(rows,"on_time_dispatch_pct"),pickAccuracy:mean(rows,"pick_accuracy_pct"),inventoryAccuracy:inventory?mean(inventory.rows,"inventory_accuracy_pct"):mean(rows,"inventory_accuracy_pct"),dockToStock:mean(rows,"dock_to_stock_hours"),spaceUtilization:mean(rows,"space_utilization_pct"),lateInbound:mean(rows,"late_inbound_pct"),costPerOrder:mean(rows,"cost_per_order")};
  const dates=rows.map(row=>row.date).filter(Boolean).sort();
  return {metrics,summary:{facility:rows[0]?.facility||"Uploaded operation",region:`${rows[0]?.region||"Unknown region"} · uploaded`,period:dates.length?`${dates[0]} to ${dates.at(-1)}`:"Uploaded period",rows:files.reduce((sum,file)=>sum+file.rows.length,0),files:files.map(file=>file.name)} as UploadSummary};
}

function constraints(metrics:Metrics):Constraint[]{return [
  {id:"inbound",label:"Inbound variability",category:"Supplier & transport",severity:metrics.lateInbound>18?"critical":metrics.lateInbound>10?"high":"healthy",value:`${metrics.lateInbound.toFixed(1)}% late`,x:14,y:26,reason:"Late arrivals compress receiving capacity and shift work into peak fulfilment windows."},
  {id:"receiving",label:"Receiving backlog",category:"Warehouse",severity:metrics.dockToStock>9?"critical":metrics.dockToStock>6?"high":"healthy",value:`${metrics.dockToStock.toFixed(1)} hrs`,x:36,y:27,reason:"Dock-to-stock time is extending inventory unavailability and consuming staging space."},
  {id:"capacity",label:"Storage capacity",category:"Facility",severity:metrics.spaceUtilization>92?"critical":metrics.spaceUtilization>87?"high":"healthy",value:`${metrics.spaceUtilization.toFixed(1)}% full`,x:56,y:48,reason:"Utilisation above the operating envelope increases travel, reshuffling and congestion."},
  {id:"picking",label:"Pick productivity",category:"Fulfilment",severity:metrics.throughput<12?"high":metrics.throughput<14?"watch":"healthy",value:`${metrics.throughput.toFixed(1)} lines/hr`,x:75,y:27,reason:"Low effective throughput is consistent with congestion and replenishment interference."},
  {id:"dispatch",label:"Dispatch service",category:"Customer promise",severity:metrics.dispatch<90?"critical":metrics.dispatch<94?"high":"healthy",value:`${metrics.dispatch.toFixed(1)}% OTD`,x:87,y:53,reason:"Late dispatch is the primary downstream service breach in the uploaded period."},
  {id:"inventory",label:"Inventory integrity",category:"Inventory",severity:metrics.inventoryAccuracy<97?"high":metrics.inventoryAccuracy<98.5?"watch":"healthy",value:`${metrics.inventoryAccuracy.toFixed(1)}% accurate`,x:52,y:75,reason:"Accuracy loss drives short picks, rework and unreliable available-to-promise signals."},
  {id:"cost",label:"Cost pressure",category:"Commercial",severity:metrics.costPerOrder>9?"high":metrics.costPerOrder>8?"watch":"healthy",value:`$${metrics.costPerOrder.toFixed(2)}/order`,x:78,y:78,reason:"Rework, congestion and labour dilution are elevating unit fulfilment cost."},
]}

export default function Home(){
  const [metrics,setMetrics]=useState(defaultMetrics);const [summary,setSummary]=useState(defaultSummary);const [uploaded,setUploaded]=useState(false);const [error,setError]=useState("");const [view,setView]=useState<"overview"|"benchmarks"|"network">("overview");const [selected,setSelected]=useState("capacity");const [busy,setBusy]=useState(false);
  const nodes=useMemo(()=>constraints(metrics),[metrics]);const selectedNode=nodes.find(node=>node.id===selected)??nodes[0];
  const scores=useMemo(()=>configs.map(config=>({...config,value:metrics[config.key],regionalPct:percentile(metrics[config.key],config.regional,config.higherBetter),globalPct:percentile(metrics[config.key],config.global,config.higherBetter)})),[metrics]);
  const overall=Math.round(scores.reduce((sum,score)=>sum+score.regionalPct,0)/scores.length);const critical=nodes.filter(node=>node.severity==="critical").length;const high=nodes.filter(node=>node.severity==="high").length;
  async function upload(event:ChangeEvent<HTMLInputElement>){const chosen=[...(event.target.files??[])];if(!chosen.length)return;setBusy(true);setError("");try{const parsed=await Promise.all(chosen.map(async file=>({name:file.name,rows:parseCsv(await file.text())})));const result=analyse(parsed);setMetrics(result.metrics);setSummary(result.summary);setUploaded(true)}catch(reason){setError(reason instanceof Error?reason.message:"Could not read these files.")}finally{setBusy(false);event.target.value=""}}
  const edges:[[string,string,string],...Array<[string,string,string]>]=[["inbound","receiving","arrival compression"],["receiving","capacity","staging congestion"],["capacity","picking","travel + interference"],["picking","dispatch","missed cut-off"],["inventory","picking","short picks"],["dispatch","cost","expedite + rework"],["capacity","inventory","cycle count disruption"]];
  return <main className="nodes-app">
    <header className="nodes-top"><div className="nodes-brand"><i>●</i><b>NODES</b><span>Supply Chain Intelligence</span></div><div className="operator"><small>ACTIVE OPERATION</small><b>{summary.facility}</b><em>{uploaded?"Uploaded analysis":"Synthetic demonstration"}</em></div><button className="avatar">TY</button></header>
    <aside className="nodes-side"><nav><button className={view==="overview"?"active":""} onClick={()=>setView("overview")}><i>⌂</i>Overview</button><button className={view==="benchmarks"?"active":""} onClick={()=>setView("benchmarks")}><i>▦</i>Benchmark matrix</button><button className={view==="network"?"active":""} onClick={()=>setView("network")}><i>⌘</i>Constraint network</button></nav><section><small>DATA SOURCES</small><div><i className="ok"/>Warehouse operations</div><div><i className="ok"/>Transport lanes</div><div><i className="ok"/>Inventory snapshot</div></section><div className="side-foot"><small>BENCHMARK COHORT</small><b>ANZ Consumer & Retail</b><span>42 regional · 318 global operations</span></div></aside>
    <section className="nodes-main">
      <div className="page-head"><div><small>OPERATIONAL DIAGNOSTIC / {summary.period}</small><h1>{view==="overview"?"Network performance overview":view==="benchmarks"?"Benchmark performance matrix":"Constraint and vulnerability network"}</h1><p>{summary.region} · {summary.rows} operational records analysed</p></div><div className="upload-actions"><a href="/samples/nodes-warehouse-daily.csv" download>Download sample</a><label className={busy?"busy":""}>{busy?"Processing…":"Upload operational CSVs"}<input type="file" accept=".csv,text/csv" multiple onChange={upload}/></label></div></div>
      {error&&<div className="upload-error" role="alert">{error}</div>}
      <div className="status-strip"><div><span>Operational benchmark</span><b>P{overall}</b><em className={overall<35?"bad":"watch"}>{overall<35?"Below peer range":"Within peer range"}</em></div><div><span>Critical constraints</span><b>{critical}</b><em className="bad">Immediate attention</em></div><div><span>High-pressure nodes</span><b>{high}</b><em className="watch">Monitor and intervene</em></div><div><span>Estimated service exposure</span><b>{Math.max(0,95-metrics.dispatch).toFixed(1)} pts</b><em className="bad">Against 95% target</em></div></div>
      {view==="overview"&&<><section className="dashboard-grid"><div className="panel benchmark-panel"><header><div><small>PERFORMANCE MATRIX</small><h2>Where this operation sits against peers</h2></div><button onClick={()=>setView("benchmarks")}>View all metrics →</button></header><div className="mini-matrix">{scores.slice(0,6).map(score=><div key={score.key}><span>{score.label}<small>{score.value.toFixed(score.key.includes("Accuracy")?2:1)}{score.unit}</small></span><div><i style={{width:`${score.regionalPct}%`}} className={score.regionalPct<25?"red":score.regionalPct<50?"amber":"green"}/><b>P{score.regionalPct}</b></div></div>)}</div></div><div className="panel exposure"><small>PRIMARY FINDING</small><div className="exposure-score"><b>01</b><span>Capacity breach is propagating into customer service</span></div><p>Space utilisation has averaged {metrics.spaceUtilization.toFixed(1)}%, above the recommended operating envelope. The data indicates receiving congestion is reducing pick throughput and contributing to dispatch misses.</p><div className="causal"><span>Late inbound</span><i>→</i><span>Dock backlog</span><i>→</i><span>Congestion</span><i>→</i><span>Service breach</span></div><button onClick={()=>setView("network")}>Trace constraint path</button></div></section><section className="panel recommendations"><header><div><small>PRIORITISED ACTIONS</small><h2>Recommended interventions</h2></div><span>Ranked by service impact, confidence and effort</span></header><div className="rec-list"><article><b>1</b><div><em>IMMEDIATE · HIGH CONFIDENCE</em><h3>Stabilise inbound appointment adherence</h3><p>Segment suppliers by arrival variability and introduce protected receiving windows for the highest-volume late cohort.</p></div><strong><span>Service impact</span>+2.1–3.4 pts</strong><i>Low effort</i></article><article><b>2</b><div><em>0–30 DAYS · HIGH CONFIDENCE</em><h3>Release the capacity pressure valve</h3><p>Remove identified excess/obsolete inventory and create temporary forward-pick overflow before the next volume peak.</p></div><strong><span>Capacity impact</span>−6–9 pts</strong><i>Medium effort</i></article><article><b>3</b><div><em>30–60 DAYS · MODERATE CONFIDENCE</em><h3>Re-slot high-frequency SKUs</h3><p>Prioritise families associated with short picks and excess travel; validate through a two-week controlled wave.</p></div><strong><span>Productivity</span>+8–14%</strong><i>Medium effort</i></article></div></section></>}
      {view==="benchmarks"&&<section className="panel full-matrix"><header><div><small>PEER-NORMALISED PERFORMANCE</small><h2>Regional and global percentile matrix</h2></div><span>Higher percentile = stronger performance</span></header><div className="matrix-head"><b>Metric</b><b>Operation</b><b>Target</b><b>ANZ cohort</b><b>Global cohort</b><b>Pressure</b></div>{scores.map(score=><div className="matrix-row" key={score.key}><span><b>{score.label}</b><small>{score.higherBetter?"Higher is better":"Lower is better"}</small></span><strong>{score.value.toFixed(score.key.includes("Accuracy")?2:1)}{score.unit}</strong><em>{score.target}</em><div><i style={{width:`${score.regionalPct}%`}}/><b>P{score.regionalPct}</b></div><div><i style={{width:`${score.globalPct}%`}}/><b>P{score.globalPct}</b></div><mark className={score.regionalPct<20?"critical":score.regionalPct<40?"high":"stable"}>{score.regionalPct<20?"Critical":score.regionalPct<40?"High":"Stable"}</mark></div>)}<footer>Benchmark cohorts are synthetic for demonstration. Production percentiles require TMX-approved, anonymised peer cohorts and consistent metric definitions.</footer></section>}
      {view==="network"&&<section className="network-layout"><div className="panel constraint-map"><header><div><small>CONSTRAINT PROPAGATION</small><h2>Select any node to inspect the pressure path</h2></div><div className="legend"><span><i className="critical"/>Critical</span><span><i className="high"/>High</span><span><i className="watch"/>Watch</span></div></header><div className="network-canvas"><svg viewBox="0 0 100 100" preserveAspectRatio="none">{edges.map(([from,to,label])=>{const a=nodes.find(n=>n.id===from)!;const b=nodes.find(n=>n.id===to)!;return <g key={`${from}-${to}`}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y}/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-1}>{label}</text></g>})}</svg>{nodes.map(node=><button key={node.id} onClick={()=>setSelected(node.id)} className={`constraint-node ${node.severity} ${selected===node.id?"selected":""}`} style={{left:`${node.x}%`,top:`${node.y}%`}}><i/><b>{node.label}</b><span>{node.value}</span></button>)}</div></div><aside className="panel node-inspector"><small>{selectedNode.category} / {selectedNode.severity}</small><h2>{selectedNode.label}</h2><strong>{selectedNode.value}</strong><p>{selectedNode.reason}</p><div><span>Regional comparison</span><b>P{scores.find(score=>selectedNode.id==="dispatch"?score.key==="dispatch":selectedNode.id==="capacity"?score.key==="spaceUtilization":selectedNode.id==="receiving"?score.key==="dockToStock":selectedNode.id==="inbound"?score.key==="lateInbound":selectedNode.id==="picking"?score.key==="throughput":selectedNode.id==="inventory"?score.key==="inventoryAccuracy":score.key==="costPerOrder")?.regionalPct}</b></div><button>Open supporting records</button></aside></section>}
    </section>
  </main>
}
